# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a9d19449a9e8ed26972c3a01d4c92e637e2bae97d012321577a6e9850478080e8d20db9058ebe2fb3f336842e03d8630df0d5deaa91a381faa6cb93abdb39f

test:
  secret_key_base: 28fb377a1cdf6f76ed39eaba6ec798d006313d3c2553e98b534cf8c29d475e45a10c88883bfa2269f97b6d7ae9a5e547ce7dc2233b188fa8351229585a866df6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
